name: 'Repository Notifications'
description: 'Generates notification messages about different events in the repository'
inputs:
  event:
    description: 'The JSON serialization of the event'
    required: true
    default: ''
  escape:
    description: 'Whether certain variables, such as refs, should be escaped. Only one escaper exists right now, which can by chosen by the value "matrix". The other value is "no".'
    require: false
    default: 'no'
outputs:
  subject: 
    description: 'The subject of the message - this will be in plain text format and quite short'
  message: 
    description: 'The actual message - this will be several lines, containing HTML formatting, including links'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'message-square'
  color: 'gray-dark'
